### ISSUE TITLE
Request for Complete Code Including Main Functions for Training and Testing

### ISSUE THREAD

**Issue by magnificent0121** [jychen229/Multimodal-reaction-yieldprediction#1]
Dear jychen229,

First of all, thank you for sharing your work and making your code available. I recently read your paper [Paper Title] and was very impressed by the research and its findings. I am keen on replicating your results and further exploring the methodologies presented in the paper.

However, while going through the repository, I noticed that some crucial parts of the code seem to be missing, specifically the main functions for training and testing the model, as well as the data loading scripts. These components are essential for fully understanding and replicating your work.

Would it be possible for you to provide the missing code, or guide me on how to properly use the existing code to train and test the model? Detailed instructions or an example script would be extremely helpful.

Thank you in advance for your assistance. I greatly appreciate your time and effort in sharing your research with the community.

Best regards,
magnificent0121

**Comment by jychen229** [comment]
Sorry for the late reply. pls check repo https://github.com/The-Real-JerryChen/reaction_yield_prediction
